### ISSUE TITLE
MediaElch: New version 2.8.18

### ISSUE THREAD

**Issue by bugwelle** [sumo300/chocolatey-packages-au#1]
Hi @sumo300 ,

a new MediaElch version 2.8.18 has been released just now. :-)

- https://mediaelch.github.io/mediaelch-doc/download.html
- https://mediaelch-downloads.ameyering.de/releases/v2.8.18/
- https://mediaelch.github.io/mediaelch-blog/posts/mediaelch-v2.8.18/

Could you please update this repository? 

(I hope it's okay to ask here, since https://github.com/mediaelch/chocolatey-mediaelch is deprecated)

Thanks and kind regards,

Andre

**Comment by bugwelle** [comment]
Ping @sumo300  :-)

**Comment by sumo300** [comment]
It should update automatically once the automated process runs (once a
day).  I'll check on it.

**Comment by sumo300** [comment]
@bugwelle before I look deeper, was anything changed with how releases were named?  I see this error which indicates something might have changed with how/where the releases are.

[1/2] mediaelch ERROR: 
     au_GetLatest failed 
     Cannot bind argument to parameter 'Path' because it is null.

**Comment by bugwelle** [comment]
IIRC, I made sure that the link format stays the same on github releases. For example:

1. https://github.com/Komet/MediaElch/releases/download/v2.8.18/MediaElch_win_2.8.18_2022-10-28_git-146c4b77.zip
2. https://github.com/Komet/MediaElch/releases/download/v2.8.16/MediaElch_win_2.8.16_2022-03-13_git-9ae0f5bd.zip

:-) 

(iirc, you use github as the binary source, right?)

Regards
Andre
(writing from mobile)

**Comment by sumo300** [comment]
@bugwelle Between your last release and now, GitHub had made some changes that caused simply parsing the release page no longer work.  I've switched to use the GitHub API and the new release should publish to Chocolatey.org shortly.

Fixed in 90c8b59fcfa8999b7beae666d10af88e2dfe659c

**Comment by sumo300** [comment]
Published - https://community.chocolatey.org/packages/MediaElch/2.8.18

**Comment by bugwelle** [comment]
Oh, thank you very much for looking into it! :)
