### ISSUE TITLE
MediaElch: Versioning format has changed

### ISSUE THREAD

**Issue by sumo300** [sumo300/chocolatey-packages-au#3]
The versioning format has changed for MediaElch requiring an update script change to grab the correct release for Windows 10 and above.

**Comment by sumo300** [comment]
@bugwelle Latest version has been published after the fix.

https://community.chocolatey.org/packages/MediaElch/2.10.0

**Comment by bugwelle** [comment]
@sumo300 Thank you very much! :-)
